export interface TripExportData {
  id: string;
  date: string;
  startTime: string;
  endTime: string;
  duration: string;
  distance: string;
  averageSpeed: string;
  maxSpeed: string;
  speedUnit: 'km/h' | 'mph';
}

export class TripExportService {
  generateSingleTripHTML(trip: TripExportData): string {
    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #1a1a1a; }
    .header { text-align: center; margin-bottom: 40px; }
    .header h1 { font-size: 28px; color: #007AFF; margin-bottom: 4px; }
    .header p { color: #888; font-size: 14px; }
    .stats-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 30px; }
    .stat-card { background: #f5f5f7; border-radius: 16px; padding: 24px; text-align: center; }
    .stat-value { font-size: 36px; font-weight: 700; color: #1a1a1a; }
    .stat-label { font-size: 14px; color: #888; margin-top: 4px; }
    .hero-stat { grid-column: span 2; background: linear-gradient(135deg, #007AFF, #5856D6); color: white; }
    .hero-stat .stat-value { color: white; font-size: 48px; }
    .hero-stat .stat-label { color: rgba(255,255,255,0.8); }
    .footer { text-align: center; margin-top: 40px; color: #ccc; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Average</h1>
    <p>Trip Report — ${this.escapeHtml(trip.date)}</p>
  </div>
  <div class="stats-grid">
    <div class="stat-card hero-stat">
      <div class="stat-value">${this.escapeHtml(trip.averageSpeed)}</div>
      <div class="stat-label">Average Speed</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">${this.escapeHtml(trip.maxSpeed)}</div>
      <div class="stat-label">Max Speed</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">${this.escapeHtml(trip.distance)}</div>
      <div class="stat-label">Distance</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">${this.escapeHtml(trip.duration)}</div>
      <div class="stat-label">Duration</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">${this.escapeHtml(trip.startTime)}</div>
      <div class="stat-label">Start Time</div>
    </div>
  </div>
  <div class="footer">Generated by Average</div>
</body>
</html>`;
  }

  generateMultiTripsHTML(trips: TripExportData[]): string {
    if (trips.length === 0) {
      return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>body { font-family: -apple-system, sans-serif; padding: 40px; }</style></head><body><h1>Average — Trip History</h1><p>No trips recorded</p></body></html>`;
    }

    const rows = trips.map(t => `
      <tr>
        <td>${this.escapeHtml(t.date)}</td>
        <td>${this.escapeHtml(t.duration)}</td>
        <td>${this.escapeHtml(t.distance)}</td>
        <td>${this.escapeHtml(t.averageSpeed)}</td>
        <td>${this.escapeHtml(t.maxSpeed)}</td>
      </tr>
    `).join('');

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, sans-serif; padding: 40px; }
    h1 { color: #007AFF; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { border: 1px solid #ddd; padding: 12px; text-align: center; }
    th { background: #007AFF; color: white; }
    tr:nth-child(even) { background: #f9f9f9; }
    .footer { text-align: center; margin-top: 20px; color: #aaa; font-size: 11px; }
  </style>
</head>
<body>
  <h1>Average — Trip History</h1>
  <p>${trips.length} trips recorded</p>
  <table>
    <thead><tr><th>Date</th><th>Duration</th><th>Distance</th><th>Avg Speed</th><th>Max Speed</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Generated by Average</div>
</body>
</html>`;
  }

  generateCSV(trips: TripExportData[]): string {
    const header = 'Date,Start Time,End Time,Duration,Distance,Average Speed,Max Speed,Unit';
    if (trips.length === 0) {
      return header;
    }
    const rows = trips.map(t =>
      `"${this.escapeCsv(t.date)}","${this.escapeCsv(t.startTime)}","${this.escapeCsv(t.endTime)}","${this.escapeCsv(t.duration)}","${this.escapeCsv(t.distance)}","${this.escapeCsv(t.averageSpeed)}","${this.escapeCsv(t.maxSpeed)}","${this.escapeCsv(t.speedUnit)}"`
    ).join('\n');
    return `${header}\n${rows}`;
  }

  async exportSingleTripPDF(trip: TripExportData): Promise<void> {
    const html = this.generateSingleTripHTML(trip);
    const RNHTMLtoPDF = require('react-native-html-to-pdf').default;
    const Share = require('react-native-share').default;
    const file = await RNHTMLtoPDF.convert({
      html,
      fileName: `average-trip-${trip.id}`,
      directory: 'Documents',
      base64: false,
    });
    await Share.open({
      url: `file://${file.filePath}`,
      type: 'application/pdf',
      title: 'Share Trip Report',
    });
  }

  async exportMultipleTripsPDF(trips: TripExportData[]): Promise<void> {
    const html = this.generateMultiTripsHTML(trips);
    const RNHTMLtoPDF = require('react-native-html-to-pdf').default;
    const Share = require('react-native-share').default;
    const file = await RNHTMLtoPDF.convert({
      html,
      fileName: `average-trip-history-${Date.now()}`,
      directory: 'Documents',
    });
    await Share.open({ url: `file://${file.filePath}`, type: 'application/pdf' });
  }

  async exportTripsCSV(trips: TripExportData[]): Promise<void> {
    const csv = this.generateCSV(trips);
    const RNFS = require('react-native-fs');
    const Share = require('react-native-share').default;
    const path = `${RNFS.DocumentDirectoryPath}/average-trips-${Date.now()}.csv`;
    await RNFS.writeFile(path, csv, 'utf8');
    await Share.open({ url: `file://${path}`, type: 'text/csv' });
  }

  private escapeHtml(str: string): string {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  private escapeCsv(str: string): string {
    return str.replace(/"/g, '""');
  }
}

export const tripExportService = new TripExportService();
